name: deploy
description: increments maven artifact version and pushes updated pom file to repo
inputs:
    registry:
      description: aws registry to push to
      required: false
    repository:
      description: repo path to push to
      required: true
    tag:
      description: tag to push
      required: true
    ip_address:
      description: ip to deploy to
      required: true
    ssh_key:
      description: ssh key to deploy
      required: true
    docker_user:
      description: user for registry
      required: true
    dockerhub_password:
      description: password specifically for dockerhub registry
      required: false
    aws_region: 
      description: region for aws
      required: false
    registry_type:
      description: the type of registry to push to
      required: true
runs:
  using: composite
  steps:
    - name: deploy
      shell: bash

      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem
        ssh-keyscan ${{ inputs.ip_address }} >> ~/.ssh/known_hosts
        scp -i ~/.ssh/key.pem scripts/docker_install.sh ubuntu@${{ inputs.ip_address }}:~/.
        ssh -i ~/.ssh/key.pem ubuntu@${{ inputs.ip_address }} << 'EOF'
        ./docker_install.sh
        
        if [[ "${{ inputs.registry_type }}" == "ecr" ]]; then
          sudo apt-get update && sudo apt-get install -y unzip curl && \
          curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip' && \
          unzip -q awscliv2.zip && \
          sudo ./aws/install --update && \
          rm -rf awscliv2.zip ./aws
          aws ecr get-login-password --region ${{ inputs.aws_region }} | sudo docker login -u ${{ inputs.docker_user }} --password-stdin ${{ inputs.registry }}
          sudo docker run ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }}
        else
          sudo docker login -u ${{ inputs.docker_user }} -p ${{ inputs.dockerhub_password }}
          sudo docker run ${{ inputs.repository }}:${{ inputs.tag }}
        fi
        EOF
