name: deploy
description: increments maven artifact version and pushes updated pom file to repo
inputs:
    registry:
      description: registry to push to
      required: true
    repository:
      description: repo to push to
      required: true
    tag:
      description: tag to add at end
      required: true
    ip_address:
      description: ip to deploy to
      required: true
    key_path:
      description: path to ssh key
      required: true
    docker_user:
      description: user for registry
      required: true
runs:
  using: composite
  steps:
    - name: deploy
      shell: bash
      run: |
        ssh-keyscan ${{ inputs.ip_address }} >> ~/.ssh/known_hosts
        scp -i ${{ inputs.key_path }} scripts/docker_install.sh ubuntu@${{ inputs.ip_address }}:~/.
        ssh -i ${{ inputs.key_path }} ubuntu@${{ inputs.ip_address }} << 'EOF'
        ./docker_install.sh
        sudo apt-get update && sudo apt-get install -y awscli
        aws ecr get-login-password --region eu-west-1 | docker login -u AWS --password-stdin ${{ inputs.registry }}
        sudo docker run ${{ inputs.registry }}/${{ inputs.repository }}:tag 
        EOF