name: AWS
on:
    push:
        branches:
            - "AWS-Infrastructure"

jobs:
    PushToECR:
        runs-on: self-hosted
        steps:
            - name: pull from docker hub
              run: docker pull odedanuka/maven:${{ github.ref_name }}

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2


            - name: Push to ECR
              id: ecr
              uses: jwalton/gh-ecr-push@v2
              with:
                  access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  region: eu-west-1
                  image: odedanuka/maven:${{ github.ref_name }}

    DeployFromECR:
        needs: PushToECR
        runs-on: self-hosted
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Pull from ECR
              id: ecr
              uses: jwalton/gh-ecr-push@v2
              with:
                  access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  region: eu-west-1
                  image: odedanuka/maven:${{ github.ref_name }}
                  direction: pull
