name : ECR Pipeline
on:
  push:
    branches: [AWS-Infrastructure]

jobs:
  build_and_push_jar:
    runs-on: self-hosted
    permissions:
        contents: write
        packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: increment version of pom and push
        uses: ./.github/actions/increment_maven_version_and_push

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1

      - name: login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: export env variable
        run: echo "REGISTRY=${{ steps.ecr-login.outputs.registry }}" >> $GITHUB_ENV 

      - name: build and push to ECR
        id: build
        env:
          REPOSITORY: github_actions
          IMAGE_NAME: hello_world_java
        run: |
          docker build -t ${{ env.REGISTRY }}/$REPOSITORY/$IMAGE_NAME:latest -t $REGISTRY/$REPOSITORY/$IMAGE_NAME:${{env.VERSION}} .
          docker push ${{ env.REGISTRY }}/$REPOSITORY/$IMAGE_NAME:${{env.VERSION}}
          docker push ${{ env.REGISTRY }}/$REPOSITORY/$IMAGE_NAME:latest
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT 
      
      - name: deploy
        uses: ./.github/actions/deploy
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ steps.build.outputs.REPOSITORY }}/${{ steps.build.outputs.IMAGE_NAME }}
          tag: latest
          ip_address: ${{ vars.DEPLOY_IP }}
          key_path: ~/.ssh/key.pem
          docker_user: AWS

      
        