name: pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # Matches your POM's requirement
          cache: 'maven'

      - name: Build and Package
        run: mvn clean package -DskipTests

      # This "saves" the JAR so other jobs can use it
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/my-app-${{github.ref}}.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn test

  deliver:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      # This "grabs" the JAR we saved in the build job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app-jar
          path: target/

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Now the file actually exists in target/my-app-1.0.0.jar
      - name: Run App
        run: java -jar target/my-app-${{github.ref}}.jar
