name : CI/CD Pipeline
on:
  push:
    branches: [retry_dh_deploy]
env:
  IMAGE: hello_world_java
jobs:
  build_and_push_jar:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: increment version of pom and push
        uses: ./.github/actions/increment_maven_version_and_push
      - name: build image
        run: | 
          docker build -t ${{ vars.DOCKER_USER }}/hello_world_java:latest \
          -t ${{ vars.DOCKER_USER }}/hello_world_java:${{ env.VERSION }}  .
          
          docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKERHUB_PUSH }}
          docker push ${{ vars.DOCKER_USER }}/${{ env.IMAGE }}:latest
          docker push ${{ vars.DOCKER_USER }}/${{ env.IMAGE }}:${{ env.VERSION }}
      - name: deploy image
        uses: ./.github/actions/deploy
        with:
          tag: latest
          ip_address: ${{ vars.DEPLOY_IP }}
          key_path: ~/.ssh/key.pem
          docker_user: ${{ vars.DOCKER_USER }}
          repository:  ${{ vars.DOCKER_USER }}/${{ env.IMAGE }}
          registry_type: dockerhub


      #- name: Set up Java and Maven environment
        #uses: actions/setup-java@v5.2.0
        #with:
          #java-version: 25
          #distribution: temurin
      
      #- name: Build and Publish jar file to packages
       # run: mvn deploy
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


